### ISSUE TITLE
Expose ledger error information

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#294]
_See also #293_

Ledger code might error, for example if a given project ID already exists. We want assign codes to these errors and expose this error information through the client API.

As a result of this it should be possible for the CLI to show an appropriate error message when a transfer transaction was sent but the user does not have enough funds

### Implementation

Currently all ledger errors are defined in `core::RegistryError`. These errors are returned from the the registry message handlers in the runtime when an error occurs and have an associated error code.

What is missing is exposing these errors properly through the client API. We have a mechanism to retrieve the result of a transaction via `TransactionApplied::result` which returns the associated `Message::Result` type. However this associated type is a result with `DispatchError` for all existing messages.

It remains to change the error type to a specific error enum for each message and ensure that this error is properly extracted from `DispatchError`

**Comment by geigerzaehler** [comment]
I’m removing the “project-health” label since this delivers value to the client consumers

**Comment by NunoAlexandre** [comment]
> It remains to change the error type to a specific error enum for each message and ensure that this error is properly extracted from DispatchError

We already have `RegistryError`, which, at the moment, is encoded in a DecodeError. In #372, I've introduced a way to attempt the conversion DispatchError -> RegistryError, which allows us to unwrap it if possible, better handle it, and provide better error information.

The quote above sounds like we'd want each message to have its own error type? We can consider that but focusing on first having the client providing better errors than the obscure/encoded DispatchError's should be the first step.

**Comment by geigerzaehler** [comment]
I’m reopening this because we don’t yet expose ledger error information properly in the client API. We also need to decide whether we want to make the error type dependent on the message.

**Comment by NunoAlexandre** [comment]
This was closed by mistake, probably wrongly automated through closing a PR referencing it.

> We also need to decide whether we want to make the error type dependent on the message.

Yes. I don't think that's beneficial overall. The upstream already suffers from ergonomic issues from having Message as a trait instead of an enum, if the error type also becomes a dependant type I only see those issues growing.

I'm started with this btw. Will address it in small chunks and invite discussion where fit.

**Comment by geigerzaehler** [comment]
> I'm started with this btw. Will address it in small chunks and invite discussion where fit.

Could you also describe the design beforehand? With incremental changes one sometimes forgets the bigger picture.

**Comment by NunoAlexandre** [comment]
> Could you also describe the design beforehand? With incremental changes one sometimes forgets the bigger picture.

I don't have a full design yet since I'm just started looking at it but overall my idea is:

- [ ] 1. Make `RegistryError` derive `thiserror` (#374)
- [ ] 2. Move the CLI `TransactionError` to the `core` and have that as the error type of every Message
- [ ] 2.1 Adjust the affected tests
- [ ] 3. Simplify `Message` to only the return value as an associated type instead of the whole `Result`. :speech_balloon: The only message returning some value back is the `SetCheckpoint`. It would be interesting, at this point, if we can simplify this bit as well.

After working on these first 3 bits (mostly the first 2), we will finally be holding error values that we can start handling properly and be able to provide useful error information. I'm confident that while working on these more opportunities to clean or improve other parts will emerge. When that happens I will open relevant issues to handle them or just update this document/invite discussion.

**Comment by geigerzaehler** [comment]
> The only message returning some value back is the `SetCheckpoint`. It would be interesting, at this point, if we can simplify this bit as well.

So the “return” value of the transaction (the checkpoint ID) can be computed locally since it is the content hash. So it is possible to remove the associated types and thus the trait for the messages.

Before we tackle that I’d like to see a concrete design of the API and some usage examples though. We want to ensure that the client is still easy to use. Since this affects a large part of the API this should be discussed thoroughly also with the application team. (I’m also curious to see how the trait affects ergonomics.)

**Comment by NunoAlexandre** [comment]
On the very same page. I have already discussed the ergonomics issue with @xla, regarding the pain it represents in the upstream. Will follow that up.

**Comment by xla** [comment]
The issue with message being a trait is that we can't easily build up general infrastructure around "any" transaction. For example would we want to match on the message type to build up our own transaction/message types. This is not easily attainable without some dyn box magic we haven't quite figured out yet, Most ergonomic would be if `Message` is an enum, imho.

**Comment by NunoAlexandre** [comment]
Thanks, @xla. I have started to work on dropping the `Message` trait to move in this direction. I will show how the overall API would work and look like if we switch to this enum that I agree to be beneficial, also when considering the trade-off.

**Comment by NunoAlexandre** [comment]
Closing this one since it has been addressed fully as for its original scope in https://github.com/radicle-dev/radicle-registry/pull/375.

The follow-up issue originated from emerging discussions is #387.
