### ISSUE TITLE
Improve build cache on CI

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#408]
Changes to, say, the README file will trigger a complete new build. We want to explore ways of caching the binaries and only rebuild them if the targets composing it have changed. For example, if a commit changes the CLI alone, only the CLI should be rebuilt and not the whole project and the node binary.

**Comment by geigerzaehler** [comment]
The caching works pretty well on a local machine because it uses timestamps. If you update only the CLI and rebuild cargo can figure out that only the CLI changed and rebuild only that. On CI this information is not available through timestamps though since we do a fresh checkout at the start of the build. I don’t have an idea for a solution to this.

**Comment by CodeSandwich** [comment]
Unfortunately you're right, this is something that may be added later: https://github.com/rust-lang/cargo/issues/6529

**Comment by geigerzaehler** [comment]
Is there something actionable in the ticket? If the cargo issue is solved we basically get this for free. Unless we have other options I’d vote to close this.

**Comment by NunoAlexandre** [comment]
Closing it 👍
