### ISSUE TITLE
runtime: Devise way to make state changes backwards-compatible

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#445]
Part of #434 // State changes

### The problem

Here lives the hairiest of the beasts. Say, we move from having the members of an organization stored as account ids to user ids. Such change fundamentally impacts the way different versions parse and handle data from the chain.

We could decide, in this early stage, to hard-fork when faced with such type of change, meaning that we would run a new, parallel network where these breaking changes would start making their way in a new, fresh ground. However, that is not going to cut once we go main net, so we are focused on learning how to do this properly as early as possible.

We need to be backwards-compatible concerning the chain state. We need to devise a way to deserialize and support older forms of the data that might still be on-chain, as well as the new one. Given the example above, when deserializing Orgs, we need to think of the old and the new variants, the one where its members were account ids and the one where they now are user ids. To help users adjust to new realities, we must provide methods for them to “migrate their data” to its latest form, not only giving control to users but also keeping everything tracked in verifiable transactions.

This category might introduce breaking changes to the CLI. To cover for this, we need to have our [client ensure that the version of the runtime the node it is connected to is not greater than the one it supports](#26). That means that the state changes that impact the CLI require a new version of the CLI to be installed. 

### How

_First, the requirements:_
📌 Support multiple versions of stored types
📌 Converge old types to their new form when deserializing the storage
📌 Offer methods for users to update their entities to the latest version form or logic

_Proposal:_
Add a tag version to every type stored on-chain. Probably the best way to go is with [serde adjacently tagged enums](https://serde.rs/enum-representations.html#adjacently-tagged).
Each version of an entity on-chain will have a corresponding variant, which will be deserialized respectively. Since we haven't introduced this before making to the ffnet, we will need to have the set up so that if no version tag is present, a variant representing the version 0 is used.

To converge and uniformize those entities, we might have to then have a struct representing the latest variant, since we don't want the system to necessarily support all the variants for all code paths. Something to think further about.

**Comment by NunoAlexandre** [comment]
See @kim's input on this at https://radicle.community/t/rambles-on-updating-the-radicle-registry/210/4

> Yaaa, one of the many issues with serde is that those tags are all strings — this means that a rename (or a typo) can break things in unexpected ways, and it’s hard to guard against this. Consider that there may exist third-party clients at some point.
>
> The other problem I see is that sum types (enums) are not so obvious to evolve in a forward-compatible way: one needs to maintain a variant for the unknown case, with enough information attached to provide meaningful error messages. I don’t think serde supports this without manual impls.

and then at https://radicle.community/t/rambles-on-updating-the-radicle-registry/210/6

> We can’t be type-safer, but we can be speling-safer by using a numeric tagging system like protocol buffers and its descendants (along with their schema evolution conventions, of course).

**Comment by geigerzaehler** [comment]
I like your proposal for serde. But in the runtime we use [`parity_scale_codec`](https://substrate.dev/rustdocs/master/parity_scale_codec/index.html) for serialization. We need to figure out whether this supports something similar.

Something that we shouldn’t forget is that we need to produce guidelines for developers so they know how to add new state or upgrade existing state.

**Comment by NunoAlexandre** [comment]
Good two points. Maybe we can get in touch with substrate to know if they suggest any approach to handle outdated state?

**Comment by CodeSandwich** [comment]
The SCALE codec has excellent support for enums: an 8-bit number denoting the variant followed by its data. That's adjacent tagging out of the box.

**Comment by CodeSandwich** [comment]
Another tool which we have, but wasn't mentioned yet is creation of a separate storage with data in a new format. The logic could be that the data is first looked up in the new storage. If it's not there, then the old storage is looked up and the data is converted on the fly. Any writing is performed only into the new storage to slowly dry up the old one.

Unfortunately I'm not aware of any easy way to run any migration logic during runtime update.

The second level of hairiness are storage updates, which can't be migrated automatically, because they need extra details. They will need to get special high priority and 0-cost message with additional data from the user. They must be submitted by the user before any further actions can be performed. Extremely annoying, we should avoid it at any cost.

**Comment by geigerzaehler** [comment]
I like your idea, @CodeSandwich. In general having versioned storage entries (via enums) is preferable to what you proposed and we should establish it as the default. The reason is that the evolution of the storage lives in one datatype. It can thus easily be tracked and all code that uses it is forced to deal with it. This prevents us from forgetting to look up the old storage. It also makes the client implementation simpler because we don’t need to look up an entity at two keys.

However, as you pointed out, there are limitations to this approach and this is where different storage scopes can be used. For example we will need this initially since we don’t have versioned storage entries yet. Changes to the keys will also require us to use new storage.

Regarding migrations: I think we should not consider migrating storage for now. There are a lot of pitfalls and the details depend very much on the specifics of the storage change and its semantics.

**Comment by geigerzaehler** [comment]
See [this post](https://radicle.community/t/registry-runtime-state-compatibility/223) for an update.

**Comment by geigerzaehler** [comment]
@CodeSandwich, @NunoAlexandre: I’d like to put the [enum proposal](https://radicle.community/t/registry-runtime-state-compatibility/223) to a vote. Shall we move forward with it or are there concerns?

**Comment by CodeSandwich** [comment]
Enums are good for me.

**Comment by NunoAlexandre** [comment]
With me as well :+1: I followed the discussion and I'm in for that approach.

**Comment by geigerzaehler** [comment]
Great! I’ll close this issue. The implementation will be handled by #496.
