### ISSUE TITLE
CI tests client backward compatibility

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#497]
The CI should be running the e2e test against the current runtime and previous versions to ensure backward compatibility of the client with at least 1 old spec version of the runtime. See [this thread](https://radicle.community/t/runtime-updates-workflow-and-testing/224). We need to run against:
- the last implementation of the previous spec version runtime
- the previous implementation of the current spec version runtime
- the current implementation of the current spec version runtime

This needs to be implemented as a script, which can be run both locally by developers and by the CI.

Until https://github.com/radicle-dev/radicle-registry/issues/492 is in place it's fine to just store the WASM binaries needed for the CI in the repository as regular binary files.

We now we can use checked-in WASM blobs with the needed runtimes. The process of updating the runtimes needs to be documented.

**Comment by geigerzaehler** [comment]
As part of this we should clearly document in the updates policy that we keep tests for the previous spec version that we are testing around to ensure that the new client works in that case, too.

**Comment by geigerzaehler** [comment]
To make this effective we need to run a node with different runtimes without having to recompile the node. I propose we add a `--runtime` option that allows one to point to a Wasm file which is then used as the initial runtime for the dev chain. The option would only work for the `dev` and `local-devnet` chains.

The rest of the initial chain state would be provided by the chain spec for the selected chain. Otherwise we would need to store the initial chain state along side the runtime in the repo.

**Comment by geigerzaehler** [comment]
@CodeSandwich: Is there something left to be done that wasn’t tackled in #536? I’m wondering why you reopend this?

**Comment by CodeSandwich** [comment]
We still have the genesis creation issue: https://github.com/radicle-dev/radicle-registry/pull/536#issuecomment-648639519 Unless we resolve it, the CI backward compatibility tests are based on coincidence.
